# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  lint:
    cmds:
      - eslint
  build:
    sources:
      - src/**/*
    generates:
      - dist/**/*
    cmds:
      - tsc
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
